# core_utils.py
import re
import difflib
import logging
from typing import Tuple, List

# Enterprise Logging Configuration
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [SYSTEM CORE] - %(levelname)s - %(message)s')

class AdvancedDataProcessor:
    """Handles deterministic data processing, bypassing unreliable LLM math."""
    
    @staticmethod
    def extract_xml_tag(text: str, tag_name: str) -> str:
        """Safely extracts data from XML tags generated by the LLM."""
        if not text:
            logging.warning(f"Empty text provided for tag extraction: <{tag_name}>")
            return ""
        try:
            # Use DOTALL to capture multi-line outputs and IGNORECASE for LLM inconsistencies
            pattern = rf'<{tag_name}>(.*?)</{tag_name}>'
            match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
            if match:
                extracted = match.group(1).strip()
                logging.info(f"Successfully extracted <{tag_name}>: {extracted[:50]}...")
                return extracted
            logging.warning(f"Failed to find tag <{tag_name}> in output.")
            return ""
        except Exception as e:
            logging.error(f"Regex extraction error for <{tag_name}>: {str(e)}")
            return ""

    @staticmethod
    def fuzzy_skill_matcher(candidate_skills_csv: str, job_skills_csv: str) -> Tuple[float, List[str]]:
        """
        Advanced Mathematical Fuzzy Matcher.
        Compares candidate skills against job requirements using string similarity
        to prevent exact-match false negatives (e.g., 'Docker' vs 'Docker Containers').
        """
        logging.info("Initiating advanced fuzzy skill matching algorithm...")
        
        if not candidate_skills_csv or not job_skills_csv:
            logging.error("Missing skill data for mathematical comparison.")
            return 0.0, [job_skills_csv] if job_skills_csv else ["No skills provided"]

        # Clean and split the lists
        c_skills = [s.strip().lower() for s in candidate_skills_csv.split(',') if s.strip()]
        j_skills = [s.strip() for s in job_skills_csv.split(',') if s.strip()]
        
        # Maintain original casing for the final report
        j_skills_original = [s.strip() for s in job_skills_csv.split(',') if s.strip()]

        matched_indices = set()
        missing_skills = []

        for i, js_lower in enumerate(j_skills):
            is_matched = False
            for cs_lower in c_skills:
                # 1. Substring Match (e.g., 'react' inside 'react.js')
                if js_lower in cs_lower or cs_lower in js_lower:
                    is_matched = True
                    break
                # 2. Levenshtein Distance Match (allows for typos, threshold > 0.65)
                similarity = difflib.SequenceMatcher(None, js_lower, cs_lower).ratio()
                if similarity > 0.65:
                    is_matched = True
                    break
            
            if is_matched:
                matched_indices.add(i)
            else:
                missing_skills.append(j_skills_original[i])

        total_required = len(j_skills)
        if total_required == 0:
            return 100.0, []
            
        match_percentage = round((len(matched_indices) / total_required) * 100, 2)
        logging.info(f"Math Complete: {match_percentage}% Match. Missing {len(missing_skills)} skills.")
        
        return match_percentage, missing_skills